gtfs: added cleanup script

diff --git a/gtfsimport b/gtfsimport
--- a/gtfsimport
+++ b/gtfsimport
@@ -23,6 +23,11 @@ if ! command -v mongoimport &> /dev/null; then
   exit 1;
 fi
 
+if ! command -v mongo &> /dev/null; then
+  echo "mongo shell not found. please install"
+  exit 1;
+fi
+
 downloadGtfs() {
   mkdir -p gtfs; cd gtfs;
 
@@ -69,11 +74,6 @@ databaseImport() {
     sed -i 's/trip_id/_id/g' trips.txt
   fi
 
-  head -n 1 agency.txt
-  head -n 1 routes.txt
-  head -n 1 stops.txt
-  head -n 1 trips.txt
-
   echo "Importing into database with URI \`$MONGO_URI\`"
 
   for F in *.txt; do
@@ -82,6 +82,10 @@ databaseImport() {
 
     mongoimport --type csv -d $2 -c $COLLEC --headerline --drop $MONGO_URI $F
   done
+
+  echo "Running cleanup script..."
+
+  mongo "$MONGO_URI" ../cleanDatabase.js
 }
 
 if [ -d "gtfs" ]; then
